config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projetos do
    resources :comentarios
    member do
      put "like" => "projetos#upvote"
      put "unlike" => "projetos#downvote"
    end
  end

  get "like" => 'projetos#like'
  get "dislike" => 'projetos#dislike'

  get 'projetos' => 'projetos#index'
  delete 'apagar' => 'projetos#destroy'
  get 'sobre' => 'paginas_iniciais#sobre'
  get 'perfil' => 'paginas_iniciais#perfil'

  get 'novo_projeto' => 'projetos#new'

  get 'home' => 'paginas_iniciais#home'

  root                 'paginas_iniciais#seguindo'

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  devise_scope :usuario do
    get 'login' => 'devise/sessions#create'
    get 'cadastrar' => 'devise/registrations#new'
    get 'editar_conta' => 'devise/registrations#edit'
  end

  resources :usuarios  do
    member do
      get :following, :followers
    end
  end
   resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :usuario
  belongs_to :projeto
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :find_projeto
	before_action :find_comentario, only: [:edit, :update, :destroy]
	before_action :authenticate_usuario!, only: [:new, :edit, :create]

	def new
		@comentario = Comentario.new
	end

	def create
    @comentario = Comentario.new(comentario_params)
    @comentario.projeto_id = @projeto.id
    @comentario.usuario_id = current_usuario.id

    if @comentario.save
      redirect_to projeto_path(@projeto)
    else
      render 'new'
    end

	end

	def edit
	end

	def update
		if @comentario.update(comentario_params)
			redirect_to projeto_path(@projeto)
		else
			render 'edit'
		end
	end

	def destroy
		@comentario.destroy
		redirect_to projeto_path(@projeto)
	end

	private

		def comentario_params
			params.require(:comentario).permit(:avaliacao, :texto)
		end

		def find_projeto
			@projeto = Projeto.find(params[:projeto_id])
		end

		def find_comentario
			@comentario = Comentario.find(params[:id])
		end

end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<div class="review">


	<div class="panel panel-default">
		<% @autor = Usuario.find(comentario.usuario_id) %>
  <div class="panel-heading"><%=link_to @autor.nome, '../usuarios/'+ @autor.id.to_s%></div>
  <div class="panel-body">
    <%= comentario.texto %>
		<% if usuario_signed_in? %>
			<% if comentario.usuario_id == current_usuario.id %>
				<div class="links btn-group pull-right">
					<%= link_to "Apagar", projeto_comentario_path(comentario.projeto, comentario), method: :delete, data: { confirm: "Você tem certeza de que deseja apagar seu comentário?" }, class: "btn btn-primary btn-xl js-scroll-trigger" %>
				</div>
			<% end %>
		<% end %>
  </div>
</div>


</div>

app/views/comentarios/_form.html.erb
<%= simple_form_for([@projeto, @projeto.comentarios.build]) do |f| %>
	<%= f.input :texto, :class =>  "form-group"%>
	<%= f.button :submit, :class => "btn btn-primary" %>
<% end %>