config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projetos do
    resources :comentarios
    member do
      put "like" => "projetos#upvote"
      put "unlike" => "projetos#downvote"
    end
  end

  get "like" => 'projetos#like'
  get "dislike" => 'projetos#dislike'

  get 'projetos' => 'projetos#index'
  delete 'apagar' => 'projetos#destroy'
  get 'sobre' => 'paginas_iniciais#sobre'
  get 'perfil' => 'paginas_iniciais#perfil'

  get 'novo_projeto' => 'projetos#new'

  get 'home' => 'paginas_iniciais#home'

  root                 'paginas_iniciais#seguindo'

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  devise_scope :usuario do
    get 'login' => 'devise/sessions#create'
    get 'cadastrar' => 'devise/registrations#new'
    get 'editar_conta' => 'devise/registrations#edit'
  end

  resources :usuarios  do
    member do
      get :following, :followers
    end
  end
   resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projeto.rb
class Projeto < ApplicationRecord
	belongs_to :usuario
	has_many :comentarios

	acts_as_votable

	has_attached_file :foto_projeto, styles: { medium: "800x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :foto_projeto, content_type: /\Aimage\/.*\z/

end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = if params[:search]
      Projeto.where('titulo LIKE ?', "%#{params[:search]}%")
    else
      Projeto.order("created_at DESC")
    end
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
    @projeto = Projeto.find(params[:id])
  end

  def upvote
    if usuario_signed_in?
      @projeto.upvote_from current_usuario
      redirect_to @projeto
    else
      redirect_to login_path
    end
  end

  def downvote
    if usuario_signed_in?
      @projeto.downvote_from current_usuario
      redirect_to @projeto
    else
      redirect_to login_path
    end
  end

  # GET /projetos/new
  def new
    @projeto = current_usuario.projetos.build

  end

  # GET /projetos/1/edit
  def edit
    if @projeto.usuario_id != current_usuario.id
      redirect_to projeto_path
    end
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = current_usuario.projetos.build(projeto_params)
    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    if @projeto.usuario_id == current_usuario.id
      respond_to do |format|

        if @projeto.update(projeto_params)
          format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
          format.json { render :show, status: :ok, location: @projeto }
        else
          format.html { render :edit }
          format.json { render json: @projeto.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:titulo, :foto_projeto, :descricao, :instrucoes, :categoria_id, :link, :term)
    end
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projetos/_form.html.erb
<div class="container my-auto">
  <div class="row">
    <div class="col-lg-10 mx-auto">

<%= form_with(model: @projeto, local: true) do |form| %>
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="comment">Título:</label>
    <%= form.text_field :titulo, id: :projeto_titulo, class:"form-control", rows: "1" %>
    <br>
  </div>

  <div class="field">
    <label for="comment">Descrição:</label>
    <%= form.text_area :descricao, id: :projeto_descricao, class:"form-control", rows: "5" , placeholder:"Descreva seu projeto resaltando sua importancia e o asunto abordado."%>
    <br>
  </div>

  <div class="field">
    <label for="comment">Instruções:</label>
    <%= form.text_area :instrucoes, id: :projeto_instrucoes, class:"form-control", rows: "5", placeholder:"Como seu projeto pode ser baixado e usado? Escreva aqui as instruções."%>
    <br>
  </div>
<br>

<div class="field">
  <label for="comment">Link do repositório do projeto:</label>
  <%= form.text_field :link, id: :projeto_link, class:"form-control", rows: "1", placeholder:"link para acesso ao projeto (gitlab, github, bit bucket...)"%>
</div>
<br>
  <div class="field">
    <%= form.label :foto_do_projeto %>
    <%= form.file_field :foto_projeto,  id: :foto_projeto, class: "img-responsive"%>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Salvar Projeto", class: "btn btn-xl btn-primary"%>
  </div>


<% end %>

</div>
</div>
</div>

app/views/projetos/edit.html.erb
      <div class="container my-auto">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Editando o Projeto</strong>
            </h1>
            <hr>

<%= render 'form' %>
<br>
<br>
<hr>
<a  class= "btn btn-secondary btn-xl js-scroll-trigger" href="javascript:history.back()" >Voltar</a>


<% prox_pagina = "../../projetos/"+@projeto.id.to_s%>
<a class="btn btn-secondary btn-xl js-scroll-trigger" href=<%=prox_pagina %>>Visualizar seu projeto</a>
<br>
<br>
</div>

</div>

app/views/projetos/index.html.erb
<body class="corpo-instagram">


<p id="notice"><%= notice %></p>
<div class="container my-auto">
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <h1 class="text-uppercase">
        <strong>Projetos</strong>
      </h1>

      <hr>
    <% @projetos.each do |projeto| %>
    <% prox_pagina = "projetos/"+projeto.id.to_s%>
      <tr>
          <article class="card">
            <%= link_to prox_pagina  do %>
              <header class="card-title">
                <h3 class="text-center font-weight-bold" ><%= projeto.titulo %></h3>
              </header>
              <div class="card-img">
                <%= image_tag projeto.foto_projeto.url, :size => '200x500', class: "rounded card-img" %>
              </div>
                <%end%>

            <div class="card-body">
              <%autor = Usuario.find(projeto.usuario_id)%>
              <strong>Desenvolvedor: <%=link_to autor.username, '../usuarios/'+autor.id.to_s%></strong>
              <p><strong>Descrição: </strong><%=truncate projeto.descricao, length: 600%></p>
            </div>
          </article>
        <br>
        <br>
    <% end %>

  <%if @projetos.count == 0%>
    <h1>Não encontramos nenhum projeto :(</h1>
  <%end%>
  <br>
  <br>
    <%if usuario_signed_in?%>
      <%if current_usuario.desenvolvedor%>
        <%= link_to "Meus projetos", perfil_path(@projeto), class: "btn btn-secondary"%>
      <%end%>
    <%end%>


    <br>
    <br>

<br>
</div>
</div>
</div>
</body>

app/views/projetos/new.html.erb
<div class="container my-auto">
    <div class="col-lg-10 mx-auto">
      <h1 class="text-uppercase">
        <strong>Novo Projeto</strong>
      </h1>
      <hr>
<%= render 'form', projeto: @projeto %>

<br>
<br>
<br>
<hr>
<a  class= "btn btn-secondary btn-xl js-scroll-trigger" href="javascript:history.back()" >Voltar</a>

<br>
<br>
<br>
</div>

</div>

app/views/projetos/show.html.erb
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong><%= @projeto.titulo%></strong>
            </h1>
            <hr>
            <div class="container-fluid">
            <figure class="figure">
              <%= image_tag @projeto.foto_projeto.url(:medium), class: "rounded" %>
            </figure>

            <p></p>

            <p>
              <%autor = Usuario.find(@projeto.usuario_id)%>
              <strong><h4>Desenvolvedor: <%=link_to autor.username, '../usuarios/'+autor.id.to_s%></h4></strong><br>
              <%= link_to like_projeto_path(@projeto), class:"like", method: :put do%>
                <button type="button" class="btn btn-info" aria-label="Left Align">
                  <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
                  <span class="badge"><%= @projeto.get_upvotes.size %></span>
                </button>
              <% end %>
              <%= link_to unlike_projeto_path(@projeto), class:"like", method: :put do%>
                <button type="button" class="btn btn-info" aria-label="Left Align">
                  <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
                  <span class="badge"><%= @projeto.get_downvotes.size %></span>
                </button>
              <% end %>
              <br>
              <br>
              <strong>Descrição:</strong><br>
              <%= @projeto.descricao %>
            </p>

            <p>
              <strong>Instruções:</strong><br>
              <%= @projeto.instrucoes %>
            </p>

            <%if usuario_signed_in?%>
            <% if @projeto.usuario_id == current_usuario.id %>
            <%= link_to 'Editar', edit_projeto_path(@projeto) %>
            <%= link_to 'Apagar', projeto_path(@projeto), method: :delete, data: {confirm: "Tem certeza?"} %>
            <% end %>
            <%end%>
            <br>
            <br>
            <br>
            <a  class= "btn btn-secondary btn-xl js-scroll-trigger" href="javascript:history.back()" >Voltar</a>
            <a class="btn btn-primary btn-xl jsprojetos-scroll-trigger" href="<%=@projeto.link%>" target="_blank">Ir para o repositório do projeto</a>
            <br>
            <br>

            <hr>
              <h3 class="text-uppercase">
                Comentários:
              </h3>
            <%if @projeto.comentarios.count == 0%>
            <header class="masthead text-center d-flex">
              <h4 >
                Este projeto ainda não possui comentários, seja o primeiro a comentar!</h4>
              </h4>
            </header>
            <%end%>

            <%= render @projeto.comentarios %>
<br>
<br>

            <%= form_for([@projeto, @projeto.comentarios.build]) do |f| %>
            <div class="form-group">
              <label for="comment">Novo Comentário:</label>
              <%= f.text_area :texto, class:"form-control", rows: "5"%>
            </div>
            <div class="actions">
              <%= f.submit "Comentar", class: "btn btn-primary btn-xl"%>
            </div>
            <%end%>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
          </div>

      </div>
    </div>