config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projetos do
    resources :comentarios
    member do
      put "like" => "projetos#upvote"
      put "unlike" => "projetos#downvote"
    end
  end

  get "like" => 'projetos#like'
  get "dislike" => 'projetos#dislike'

  get 'projetos' => 'projetos#index'
  delete 'apagar' => 'projetos#destroy'
  get 'sobre' => 'paginas_iniciais#sobre'
  get 'perfil' => 'paginas_iniciais#perfil'

  get 'novo_projeto' => 'projetos#new'

  get 'home' => 'paginas_iniciais#home'

  root                 'paginas_iniciais#seguindo'

  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  devise_scope :usuario do
    get 'login' => 'devise/sessions#create'
    get 'cadastrar' => 'devise/registrations#new'
    get 'editar_conta' => 'devise/registrations#edit'
  end

  resources :usuarios  do
    member do
      get :following, :followers
    end
  end
   resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<html>
  <head>
    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">


        <title>CoffeeBreak</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>
      <body>

        <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light navbar-fixed-top" id="mainNav">

          <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="<%=root_path%>">CoffeeBreak</a>
            <button class="navbar-toggler navbar-toggler-left" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                <% if usuario_signed_in? %>
                <%saudacao = "Olá "+ current_usuario.nome + "!"%>
                <strong><%= link_to saudacao, perfil_path, :class => 'nav-link js-scroll-trigger' %></strong>
                <%= link_to "Editar conta", editar_conta_path, :class => 'nav-link js-scroll-trigger'  %>
                <%= link_to "Logout", destroy_usuario_session_path, method: :delete, :class => 'nav-link js-scroll-trigger'  %>
                <% else %>
                <%= link_to "Cadastre-se", cadastrar_path, :class => 'nav-link js-scroll-trigger'  %>
                <%= link_to "Login", login_path, :class => 'nav-link js-scroll-trigger'  %>
                <% end %>
                <%= link_to "Sobre", sobre_path, :class => 'nav-link js-scroll-trigger'  %>
              </ul>

              <li class="navbar-nav ml-auto navbar-right" id="navbarResponsive">
              <% if usuario_signed_in? %>
                <%if current_usuario.admin? %>
                  <a class="nav-link js-scroll-trigger"href="/admin">Admin</a>
                  <%end%>
              <%end%>
            </li>


              <ul class="navbar-nav ml-auto navbar-right" id="navbarResponsive">
                <%= link_to "Projetos", projetos_path, :class => 'nav-link js-scroll-trigger'  %>
                <% if usuario_signed_in?%>
                <% if current_usuario.desenvolvedor%>
                  <%= link_to "Crie um novo projeto", new_projeto_path, :class => 'nav-link js-scroll-trigger' %>
                 <% end %>
                <%end%>
              </ul>


            </div>

            <div class="navbar-form navbar-right" id="navbarResponsive">
            <%= form_tag(projetos_path, :method => "get", id: "search-form", :class => "navbar-form navbar-left", :style => "display:inline;") do %>

              <div class="input-group custom-search-form">
                <%= text_field_tag :search, params[:search], placeholder: "Procure projetos", :class => "form-control" %>
                <span class="input-group-btn">
                  <%= button_tag(type: "submit", class: "btn", name: nil) do %>
                    <span class="glyphicon glyphicon-search"></span>
                  <% end %>
                </span>
              </div>
            <% end %>
          </div>
        </div>

      </nav>

      <br>
      <br>

      <div class="container">
          <%= flash_messages %>
      </div>
          <!--
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          -->

      <%= yield %>
    </meta>
  </body>
</html>